name: My First Workflow
on: 
  workflow_dispatch: 
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: second step
        run: pwd
      - name: first step
        run: echo " hello world"
      
